### ISSUE TITLE
Naming "knowledge map"

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/TranslatorInterchangeAPI-Specification#1]
@vdancik mentioned that the term "knowledge map" is already used in another context, and something like "answer map" might be better to avoid confusion. Other suggestions?

**Comment by patrickkwang** [comment]
@cmungall and @edeutsch may also have input.

**Comment by edeutsch** [comment]
I don't know what this other context is, so not sure. I have a vague unease that "knowledge map" isn't the right term, but I don't have a great idea on what would be better. We could call it a result_map. That terminology seems appropriate since each instance is the mapping in the context of a result. Or maybe result_query_binding?

**Comment by patrickkwang** [comment]
I'm looking into a structure more like this:
```
Answer:
  type: object
  properties:
    score:
      type: number
    bindings:
      type: object
      additionalProperties:
        type: string
  additionalProperties: true
```
which would allow us to include a score and other metadata. It's also very close to what's used [here](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/master/API/0.9.0/TranslatorReasonersAPI_0.9.0.yaml).
